ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

= Contexto

== Introducción

=== La contratación como palanca de transformación del modelo económico y social

*La contratación municipal representa una inyección de recursos muy relevante en la economía.*
El Ayuntamiento de Barcelona tiene un volumen de contratación anual de unos 600 millones de euros en bienes y servicios (casi la cuarta parte del presupuesto municipal), cifra que supera los 1.000 millones de euros si se consolida todo el grupo municipal.
Estas cifras convierten al Ayuntamiento en uno de los motores de actividad económica en la ciudad.

*La contratación pública administrativa se convierte así en una de las principales herramientas con respecto a la política económica municipal* y, por lo tanto, en una de las palancas clave para impulsar la transformación del modelo económico y social de Barcelona.

*El Ayuntamiento quiere* aprovechar estos recursos para *impulsar un nuevo modelo de gobierno y gestión de las TIC en el Ayuntamiento*, como motor de esta transformación, y convertirlas en un instrumento para el crecimiento del tejido económico del sector de las TIC y de la innovación de la ciudad.

=== Las TIC y la innovación como elementos centrales de transformación

*La evolución de las TIC en general, y el uso generalizado de internet en concreto, están transformando prácticamente todos los sectores de nuestra sociedad y de nuestra economía* (desde la manufactura y el transporte, hasta la energía o la atención sanitaria).
La información y los datos se han convertido en uno de los bienes más valiosos y preciados.
Estos son el producto principal de lo que se denomina _economía del conocimiento o economía digital_.

En este nuevo contexto, las empresas son, en muchos casos, más valoradas por sus ideas y la información que gestionan que por sus activos materiales.

Este nuevo paradigma, donde destaca internet como canal y herramienta de producción, favorece el nacimiento de nuevos intermediarios, cuyo valor añadido es ordenar la información y ponerla a disposición de los usuarios finales.
De este modo, podemos encontrar ejemplos tan sorprendentes como los siguientes:

* Una de las empresas de transporte privado más grandes del mundo... no tiene vehículos propios (Uber).
* El mayor proveedor de alojamientos del mundo... no tiene propiedades (Airbnb).
* Una de las compañías de telefonía más utilizadas... no es propietaria de la infraestructura de telecomunicaciones (Skype).
* El más popular de los medios de comunicación... no crea contenidos (Facebook).
* Una de las compañías de exhibición de contenidos audiovisuales más grandes del mundo... no tiene ningún cine ni canal de televisión (Netflix).

Sin duda, todos ellos son ejemplos de cómo *el uso de las TIC, y especialmente los servicios digitales, se ha convertido en el motor de una transformación de los servicios y sectores económicos vinculados.*

*Es en este contexto en el que las ciudades como Barcelona afrontan la necesidad de transformar sus maneras de hacer* y de buscar nuevas estrategias basadas en la tecnología y la innovación, para lograr un crecimiento económico más equitativo y sostenible que facilite una realización de las competencias municipales con eficiencia y justicia social.

=== Transición hacia la soberanía tecnológica

El 6 de octubre de 2016 la comisionada de Tecnología e Innovación Digital presentó el
*Plan Barcelona digital 2017-2020: transición hacia la soberanía tecnológica*, cuya misión es “resolver los retos de la ciudad y de las personas a través de un uso más democrático de la tecnología. Impulsar la innovación tecnológica y digital, para un gobierno más abierto, como herramienta para el desarrollo de una economía plural que fomente la transformación social y ambiental, y que favorezca el empoderamiento ciudadano”.

*El plan*, que *se estructura en tres ejes*, es una muestra de la voluntad de Barcelona de liderar una transición hacia la soberanía tecnológica, del gobierno y de la ciudadanía, que permita hacerlos partícipes, para decidir y actuar sobre las prioridades y estrategias en el uso de la tecnología en la ciudad:

* Gobierno y ciudad: gobierno abierto y eficiente.
Tecnología para la transformación e innovación pública a través de lo siguiente:
** Transformación e innovación digital del sector público.
** Disponer de una infraestructura de datos pública y abierta para desarrollar aplicaciones innovadoras basadas en datos

* Empresas y entidades sociales: desarrollo del tejido socioeconómico digital y del ecosistema de innovación local, con los siguientes fines:
** Promover y fortalecer el ecosistema y el tejido económico local, favoreciendo una economía plural y con retorno social.
** Facilitar el acceso de las pymes a la compra pública y fomentar la creación de empleo de calidad.

* Ciudadanía: empoderamiento de la ciudadanía.
** Disponer de una amplia oferta de formación y capacitación digital personalizada para los diferentes colectivos, para facilitar una democracia activa y participativa.
** Fomentar un empleo de calidad y permitir una soberanía digital de la ciudadanía de Barcelona.

Barcelona quiere aprovechar las oportunidades que brindan la tecnología y la innovación basada en las TIC para mejorar los servicios que el Ayuntamiento presta a la ciudad poniendo el foco en el bienestar de los ciudadanos y las ciudadanas.

*El compromiso es enfocar los retos reales que los ciudadanos manifiestan y centrar los esfuerzos en la prestación de unos servicios públicos actualizados y de mayor calidad, en el impulso de una economía más sostenible y colaborativa, en el fomento del talento del tejido económico local y en el empoderamiento de los ciudadanos.*

== ¿Por qué esta guía?
//revisar

Esta guía proporciona una visión global de la estrategia municipal sobre la compra de tecnología y servicios tecnológicos, con el objetivo de facilitar la comprensión de las diferentes medidas estratégicas y de las cláusulas contractuales que permiten aplicar los planteamientos del Ayuntamiento en este ámbito.

=== Destinatarios de la guía

Esta guía se ha elaborado pensando en los responsables de las diferentes áreas y órganos municipales, directivos y gestores de servicios públicos, técnicos municipales, proveedores TIC del Ayuntamiento, ciudadanos y cualquier persona con un interés por la compra o provisión de servicios tecnológicos, y ofrece información detallada sobre el por qué, el qué y el cómo de la contratación de TIC, incluyendo explicaciones sobre el contenido de las medidas y su aplicación.
Concretamente, los destinatarios son los siguientes:

* Los responsables de las diferentes áreas y órganos municipales, directivos y gestores de servicios públicos que ejercen las funciones de planificación y ejecución de procedimientos de contratación (compradores públicos), para que tengan una visión general con respecto a la estrategia del Ayuntamiento en el ámbito de las TIC.

* Los técnicos municipales responsables de iniciar un procedimiento de contratación, para los que constituye una guía para facilitar la materialización de las diferentes medidas.

* Empresas del ámbito de las TIC que sean actualmente proveedores municipales o que tengan voluntad de serlo, con el objetivo de que conozcan qué aspectos hay que observar en relación con la prestación de sus servicios y el proceso de contratación.

* Finalmente, la publicación de esta guía resulta un ejercicio de transparencia para los ciudadanos, ya que permite profundizar en el conocimiento, el seguimiento y el control de las medidas que está tomando el Ayuntamiento para alcanzar los objetivos fijados.

=== Elaboración de la guía y puesta en marcha

Esta guía es *resultado del trabajo conjunto de diferentes áreas del Ayuntamiento y del IMI, con la participación del sector empresarial.*

* Se ha trabajo conjuntamente en la elaboración del contenido:
** Con técnicos y referentes del IMI en las diferentes materias TIC objeto de esta guía.
** Con técnicos y referentes del Área de Administración, de Servicios Jurídicos y de la Intervención del IMI con respecto a la adecuación y validez jurídica de los planteamientos, las medidas propuestas y las cláusulas.

* Se ha contado con el apoyo y el asesoramiento de la Dirección de Coordinación de Contratación del Ayuntamiento de Barcelona.
* Asimismo, se han llevado a cabo varias sesiones de trabajo con las empresas y proveedores de servicios TIC al Ayuntamiento con la finalidad de enriquecer el proceso.

Para la puesta en marcha de las medidas y los planteamientos que se recogen, se *están llevando a cabo las siguientes acciones*:

* Se habilitará un espacio web en el que se podrá acceder a información relevante sobre el proceso de transformación y la estrategia municipal en lo que se refiere a la compra pública.
* Se está trabajando desde el Ayuntamiento para poner en marcha un _marketplace_: un espacio de diálogo e interrelación entre proveedores, ciudadanos y el Ayuntamiento que permitirá acceder a toda la información sobre los procedimientos de contratación abiertos y sobre los futuros contratos en licitación, y disponer de información e indicadores sobre los resultados de la ejecución de los contratos ya finalizados (entre otra información).
El objetivo es doble: dar más visibilidad y transparencia a los procesos de contratación y facilitar el contacto entre empresas para generar alianzas, proyectos de innovación y conocimiento de buenas prácticas con respecto al abastecimiento de servicios TIC a la Administración.

* Finalmente, con el fin de materializar todos estos cambios, se llevarán a cabo una serie de cambios organizativos que permitan implementar esta estrategia de manera efectiva.

== Marco de referencia: la compra pública sostenible

Las administraciones públicas pueden utilizar sus contratos como eficaces instrumentos de lucha contra la exclusión social, de generación de empleo de calidad, de impulso de la igualdad efectiva de hombres y mujeres y de preservación del medio ambiente.

*La Directiva de contratación pública 2014/24/UE*, aprobada por el Parlamento Europeo y el Consejo, en su considerando n.º 2, señala: “*La contratación pública tiene un papel clave en la Estrategia Europa 2020*, que es uno de los instrumentos basados en el mercado que deben utilizarse *para conseguir un crecimiento inteligente, sostenible e integrador*, y garantiza, al mismo tiempo, un uso más eficiente de los fondos públicos, facilita la participación de las pequeñas y medianas empresas en la contratación pública y *permite que los contratantes utilicen mejor la contratación pública en apoyo de objetivos sociales comunes”*.

Es en este contexto en el que el Ayuntamiento de Barcelona, con la voluntad de definir una nueva estrategia de contratación, toma una serie de medidas destinadas a poner en marcha una estrategia de contratación sostenible que permita favorecer una mejora general de las condiciones laborales y medioambientales de los sectores productivos locales, promoviendo el bien común.

*La estrategia municipal se estructura en tres ejes de actuación:*

* *Conjunto de medidas sociales*.
Medidas sociales, de inclusión social, de igualdad de género y de justicia social para incentivar la contratación de las obras, los suministros y los servicios con empresas y profesionales que ejecuten los contratos públicos con un modelo de negocio basado en salarios dignos, contratación laboral estable con protección de la salud laboral y comportamiento ético.

* *Conjunto de medidas ambientales*.
Incorpora las instrucciones técnicas para la aplicación de criterios de sostenibilidad para doce ámbitos de actividad concretos y una relación de posibles criterios ambientales para los ámbitos fuera de la aplicación de las instrucciones técnicas.

* *Conjunto de medidas transversales asociadas a la tecnología y la innovación*. Este tercer eje consta de un conjunto de líneas de actuación destinadas a lo siguiente:
** Incrementar la soberanía tecnológica del Ayuntamiento.
** Disponer de una infraestructura de datos pública y abierta que garantice la privacidad de los ciudadanos e incremente la transparencia de la Administración municipal.
** Incorporar nuevas metodologías que permitan el desarrollo de servicios digitales innovadores, eficientes y focalizados en las necesidades de los ciudadanos.

//Falta imatge
[cols=`^,,^,^`, width="20%"]
|============================
2.1+^|[OBJ] *DECRETO DE ALCALDIA*

¬-----------l---------------¬
|MEDIDAS SOCIALES ^|MEDIDAS AMBIENTALES
2+^|*TIC E INNOVACIÓN*
|============================

Medidas que tienen un efecto multiplicativo sobre los otros dos ejes (sociales y ambientales), ya que una buena gestión de la innovación y la tecnología es un elemento clave a la hora de desarrollar mejores políticas sociales (vivienda social, reducción de la pobreza o creación de puestos de trabajo de futuro) y ambientales, y potenciar su efecto.

Un ejemplo de esta voluntad es la afiliación del Ayuntamiento de Barcelona al proyecto _Electronics Watch (http://electronicswatch.org/ca)_ para la compra pública responsable y los derechos laborales en la industria de la electrónica.
De esta afiliación se deriva, también, la inclusión de unas determinadas cláusulas en los contratos de compra de equipos electrónicos con el objetivo de respetar los derechos laborales y las normas de seguridad en las cadenas mundiales de suministro de productos TIC.

Esta estrategia ha tomado forma con *la publicación de un decreto de alcaldía de contratación pública sostenible del Ayuntamiento de Barcelona (S1/D/2017-1271, de 24 de abril)*, en el que se establece, en el primer artículo, la voluntad de impulsar una contratación pública que integra, en la causa y el objeto del contrato público municipal, medidas sociales, ambientales, éticas y de innovación:

* Que garanticen los derechos laborales, sociales y ciudadanos de las personas que ejecuten el contrato público y de las personas destinatarias o usuarias de este.
* Que impulsen una economía local circular y sostenible.
* Y que promuevan la actividad económica de las medianas y pequeñas empresas, de las microempresas locales y, singularmente, de las empresas sociales.

*El decreto incorpora la Guía de contratación pública social y la Guía de contratación pública ambiental* para dar más visibilidad y acelerar la incorporación de las medidas y cláusulas de carácter social y ambiental en los futuros pliegos, y prevé la posible incorporación de medidas o instrucciones en otros ámbitos.

*Esta guía tiene como objeto recoger las medidas asociadas a este tercer eje (las TIC y la innovación).*

== Concepto de contratación TIC y compra para la innovación

=== Contratación tecnológica

Hablamos de contratación TIC para referirnos a cualquier proceso de adquisición, mantenimiento o mejora de cualquier elemento asociado a los siguientes ámbitos:

* *Las redes e infraestructuras de comunicación.*
Incluye toda aquella infraestructura que permite la comunicación entre dos terminales o equipos informáticos.
* *_Hardware_ o elemento físico de comunicación y procesamiento de la información (terminales).*
Los terminales actúan como punto de acceso a la sociedad de la información y, por eso, son de suma importancia y constituyen uno de los elementos que más han evolucionado y evolucionan: es continua la aparición de terminales que permiten aprovechar la digitalización de la información y la creciente disponibilidad de infraestructuras para el intercambio de esta información digital.
A todo ello han contribuido distintas novedades tecnológicas que han coincidido en el tiempo para favorecer un entorno propicio, puesto que la innovación en terminales va unida a la innovación en servicios, ya que usualmente el terminal es el elemento que limita el acceso.

* *_Software._*
Es el conjunto de los programas informáticos, procedimientos y documentación que desempeñan alguna tarea en un ordenador.

* *Los servicios digitales.*
Se entiende por servicio digital todo servicio que se pone a disposición del usuario —a través de internet o de cualquier adaptación o aplicación de los protocolos, plataformas o la tecnología utilizada por internet o cualquier otra red, pública o privada— y mediante el cual se prestan servicios equivalentes a través de accesos en línea.
Se caracteriza porque es esencialmente automático y no es viable en ausencia de la tecnología de la información.
En línia y se caracteritza porqué es esencialmente automático y no es viable en ausencia de la tecnología de la información.

=== La compra pública para la innovación

El Ayuntamiento quiere participar de las ventajas de la compra para la innovación y se ha fijado como estrategia la introducción de una serie de acciones para hacer que sus compras fomenten la innovación con la finalidad de garantizar e incrementar el bienestar de las personas que viven en el territorio.

La contratación pública para la innovación es una nueva manera de contratar y de dialogar con el mercado para responder a las necesidades que no encuentran solución en los procesos de contratación ordinaria.

Este nuevo enfoque de las compras públicas se postula como una herramienta fundamental para obtener soluciones que se ajusten mucho más a las demandas reales de la sociedad y para ayudar a las empresas a ser más competitivas.
El Ayuntamiento se posiciona como tractor de innovación del mercado.

Se pretende, así, estimular la creación de nuevos mercados, nuevos productos, nuevos métodos de producción o nuevas maneras de organización o suministro.
Se trata de pasar de una compra pública muy detallada en los pliegos técnicos, y a menudo adjudicada con criterios del mejor precio, a una compra que trabaja por definición de retos y soluciones sostenibles innovadoras, a menudo con la implicación de multiplicidad de actores.
Este nuevo planteamiento permite la entrada de ideas y de soluciones innovadoras que aportan eficiencia.

*Para más detalles, consulte la Guía de compra para la innovación editada por el Ayuntamiento de Barcelona.*

=== Ámbitos de aplicación de los servicios TIC

Los ámbitos de aplicación de esta guía, con respecto a la tecnología, son, principalmente, los siguientes:

* *Adquisición de software y soluciones TIC:* compra de aplicaciones y soluciones TIC, así como de licencias para su uso.

* *Desarrollo de servicios y aplicaciones:* desarrollo, mantenimiento y evolución de soluciones TIC eficientes y productivas para la ciudadanía y los empleados municipales.

* *Infraestructuras TIC:* despliegue, seguimiento y control de aplicaciones, servicios y sistemas TIC del Ayuntamiento, incluyendo la administración de tareas relacionadas con el funcionamiento de la infraestructura y las aplicaciones.

=== Ámbitos de aplicación de la compra para la innovación

Barcelona propone una amplia definición de promoción de la innovación en su estrategia:

* Entiende la compra pública para la innovación (CPI) como la compra pública que aprovecha las soluciones innovadoras (productos, tecnologías y procesos) que surgen en el proceso de compra para fomentar un mayor impacto en el crecimiento sostenible e integrador de la sociedad.

* Barcelona también promueve con los mismos objetivos la inclusión de la innovación en sus compras regulares; es decir, la compra de cualquier producto o servicio con un componente de innovación.

*Para más detalles, consulte la Guía de compra para la innovación editada por el Ayuntamiento de Barcelona.*
